ktra02/Models/ErrorViewModel.cs
namespace ktra02.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ktra02/Models/HangHoa.cs
using System;
using System.Collections.Generic;

namespace ktra02.Models;

public partial class HangHoa
{
    public int MaHang { get; set; }

    public int MaLoai { get; set; }

    public string TenHang { get; set; } = null!;

    public decimal? Gia { get; set; }

    public string? Anh { get; set; }

    public virtual LoaiHang MaLoaiNavigation { get; set; } = null!;
}

ktra02/Models/HangHoaPartial.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace ktra02.Models
{
    // Bước 1: Khai báo class HangHoa là partial và gán Metadata cho nó
    //meta data dùng để liên kết class HangHoa với class HangHoaMetaData
    [ModelMetadataType(typeof(HangHoaMetaData))]
    public partial class HangHoa
    {
        // Để trống, không cần viết gì thêm
    }

    // Bước 2: Tạo class Metadata chứa các luật Validation
    public class HangHoaMetaData
    {
        [Required(ErrorMessage = "Tên hàng hóa là bắt buộc")]
        public string TenHang { get; set; }

        [Required(ErrorMessage = "Đơn giá là bắt buộc")]
        [Range(100, 5000, ErrorMessage = "Giá phải nằm trong khoảng từ 100 đến 5000")]
        public double? Gia { get; set; }

        [Required(ErrorMessage = "Ảnh sản phẩm là bắt buộc")]
        // Regex kiểm tra đuôi file ảnh (không phân biệt hoa thường)
        [RegularExpression(@"^.*\.(jpg|png|gif|tiff)$", ErrorMessage = "Tên file ảnh phải có đuôi: .jpg, .png, .gif, .tiff")]
        public string Anh { get; set; }
    }
}

ktra02/Models/LoaiHang.cs
using System;
using System.Collections.Generic;

namespace ktra02.Models;

public partial class LoaiHang
{
    public int MaLoai { get; set; }

    public string TenLoai { get; set; } = null!;

    public virtual ICollection<HangHoa> HangHoas { get; set; } = new List<HangHoa>();
}

ktra02/Models/QlhangHoaContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ktra02.Models;

public partial class QlhangHoaContext : DbContext
{
    public QlhangHoaContext()
    {
    }

    public QlhangHoaContext(DbContextOptions<QlhangHoaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<HangHoa> HangHoas { get; set; }

    public virtual DbSet<LoaiHang> LoaiHangs { get; set; }

    public virtual DbSet<TblAccount> TblAccounts { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=QLHangHoa;Trusted_Connection=True;TrustServerCertificate=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<HangHoa>(entity =>
        {
            entity.HasKey(e => e.MaHang);

            entity.ToTable("HangHoa");
           
            // Thêm dòng này để EF biết SQL sẽ tự sinh mã, Code không cần gửi số 0 xuống
            entity.Property(e => e.MaHang).ValueGeneratedOnAdd();
           

            entity.Property(e => e.Anh).HasMaxLength(100);
            entity.Property(e => e.Gia).HasColumnType("numeric(18, 0)");
            entity.Property(e => e.TenHang).HasMaxLength(50);

            entity.HasOne(d => d.MaLoaiNavigation).WithMany(p => p.HangHoas)
                .HasForeignKey(d => d.MaLoai)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HangHoa_LoaiHang");
        });

        modelBuilder.Entity<LoaiHang>(entity =>
        {
            entity.HasKey(e => e.MaLoai);

            entity.ToTable("LoaiHang");

            entity.Property(e => e.TenLoai).HasMaxLength(50);
        });

        modelBuilder.Entity<TblAccount>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable("tblAccount");

            entity.Property(e => e.Password)
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.Username)
                .HasMaxLength(10)
                .IsFixedLength();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

ktra02/Models/TblAccount.cs
using System;
using System.Collections.Generic;

namespace ktra02.Models;

public partial class TblAccount
{
    public int Uid { get; set; }

    public string? Username { get; set; }

    public string? Password { get; set; }
}

ktra02/Controllers/HomeController.cs
using System.Diagnostics;
using ktra02.Models;
using Microsoft.AspNetCore.Mvc;

namespace ktra02.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly QlhangHoaContext _context;


        public HomeController(ILogger<HomeController> logger, QlhangHoaContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            var hanghoa = _context.HangHoas.Where(p => p.Gia >= 100).ToList();
            return View("vvd_maincontent",hanghoa);
        }
        public IActionResult GetProductsByLoai(int maLoai)
        {
            var products = _context.HangHoas.Where(p => p.MaLoai == maLoai).ToList();
            // SỬA DÒNG NÀY: Trả về _ProductList thay vì vvd_maincontent
            return PartialView("_ProductList", products);
        }

        // 1. Action GET: Hiển thị form thêm mới
        [HttpGet]
        public IActionResult Create()
        {
            // Lấy danh sách Loại hàng đưa vào ViewBag để hiển thị Dropdown
            ViewBag.MaLoai = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(_context.LoaiHangs, "MaLoai", "TenLoai");
            return View();
        }

        // 2. Action POST: Xử lý khi người dùng nhấn nút Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public IActionResult Create(HangHoa hangHoa)
        // 1. Đổi kiểu trả về thành async Task<IActionResult>
        public async Task<IActionResult> Create(HangHoa hangHoa)
        {
            // 1. Loại bỏ check null cho bảng phụ (Loại hàng) vì ta chỉ cần MaLoai
            ModelState.Remove("MaLoaiNavigation");
            // Kiểm tra xem dữ liệu có thỏa mãn các Annotation ở Bước 1 không
            if (ModelState.IsValid)
            {
                try
                {
                    // 2. Thêm vào context
                    _context.Add(hangHoa);

                    // 3. Dùng SaveChangesAsync thay vì SaveChanges
                    await _context.SaveChangesAsync();

                    // 4. Kiểm tra lại tên Action này có đúng không? 
                    // Nếu bạn muốn về trang danh sách, thường là "Index"
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    // Bắt lỗi nếu có (VD: Lỗi kết nối DB, lỗi khóa ngoại)
                    ModelState.AddModelError("", "Lỗi lưu dữ liệu: " + ex.Message);
                }
            }

            // Nếu không hợp lệ (ví dụ nhập giá 90), thì load lại form và hiển thị lỗi
            // Nhớ load lại Dropdown Loại hàng nếu không sẽ bị lỗi null
            ViewBag.MaLoai = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(_context.LoaiHangs, "MaLoai", "TenLoai", hangHoa.MaLoai);
            return View(hangHoa);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ktra02/ViewComponents/LoaiHangMenuViewComponent.cs
using ktra02.Models;
using Microsoft.AspNetCore.Mvc;

namespace ktra02.ViewComponents
{
    public class LoaiHangMenuViewComponent: Microsoft.AspNetCore.Mvc.ViewComponent
    {
        private readonly QlhangHoaContext _context;

        public LoaiHangMenuViewComponent(QlhangHoaContext context)
        {
            _context = context;
        }

        public IViewComponentResult Invoke()
        {
            var loaihang = _context.LoaiHangs.OrderBy(x => x.TenLoai).ToList();
            return View(loaihang);
        }
    }
}

ktra02/Views/Shared/vvd_Header.cshtml
<!-- Begin Header -->
<div class="header">
	<div class="header_top">
		<div class="logo">
			<a href="index.html"><img src="images/logo.png" alt="" /></a>
		</div>
		<div class="cart">
			<p>
				Welcome to our Online Store! <span>Cart:</span><div id="dd" class="wrapper-dropdown-2">
					0 item(s) - $0.00
					<ul class="dropdown">
						<li>you have no items in your Shopping cart</li>
					</ul>
				</div>
			</p>
		</div>
		<div class="clear"></div>
	</div>
	<div class="header_bottom">
		<div class="menu">
			
			<ul>
                @await Component.InvokeAsync("LoaiHangMenu")
				<li><a href="Home/Create">VU VAN DOAN</a></li>
			</ul>
		</div>
		<div class="search_box">
			<form>
				<input type="text" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}">
				<input type="button" value="">
			</form>
		</div>
		<div class="clear"></div>
	</div>
</div>
<!-- End Header -->

ktra02/Views/Shared/vvd_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ktra02</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ktra02.styles.css" asp-append-version="true" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />

</head>
<body>
    <header>
        @* <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ktra02</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav> *@
        <partial name="vvd_Header" />
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        <div style="clear:both"></div>
    </div>
    <div style="clear:both"></div>
    <footer class="border-top footer text-muted">
        <partial name="vvd_Footer" />   
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ktra02/Views/Shared/vvd_footer.cshtml
@* <div style="clear:both"></div>
<div class="footer">
	<div class="wrap">
		<div class="section group">
			<div class="col_1_of_4 span_1_of_4">
				<h4>Information</h4>
				<ul>
					<li><a href="about.html">About Us</a></li>
					<li><a href="contact.html">Customer Service</a></li>
					<li><a href="#">Advanced Search</a></li>

				</ul>
			</div>
			<div class="col_1_of_4 span_1_of_4">
				<h4>Why buy from us</h4>
				<ul>
					<li><a href="about.html">About Us</a></li>
					<li><a href="contact.html">Customer Service</a></li>
					<li><a href="#">Privacy Policy</a></li>

				</ul>
			</div>
			<div class="col_1_of_4 span_1_of_4">
				<h4>My account</h4>
				<ul>
					<li><a href="contact.html">Sign In</a></li>
					<li><a href="index.html">View Cart</a></li>
					<li><a href="#">My Wishlist</a></li>

				</ul>
			</div>
			<div class="col_1_of_4 span_1_of_4">
				<h4>Contact</h4>
				<ul>
					<li><span>+91-123-456789</span></li>
					<li><span>+00-123-000000</span></li>
				</ul>
			</div>
		</div>
	</div>
</div>
<!-- End Footer --> *@